### ISSUE TITLE
Замечания по Radix

### ISSUE THREAD

**Issue by alexey-malov** [arina-kaa/OOP#2]
https://github.com/arina-kaa/OOP/blob/e3e7619da0c0c49d54e70f258ca530d0c8eba708/lab_01_02_06/01_02_06.cpp#L103-L108

- [x] value должен здесь быть строковым. Преобразованием из исходной системы счисления в конечную должен заниматься другой код

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/e3e7619da0c0c49d54e70f258ca530d0c8eba708/lab_01_02_06/01_02_06.cpp#L141

- [x] объекты следует передавать по константной ссылке, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению

- [x] Radix - неудачное имя для функции. Лучше назвать так: ConvertNumber(number, sourceNotation, destinationNotation, wasError)

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/e3e7619da0c0c49d54e70f258ca530d0c8eba708/lab_01_02_06/01_02_06.cpp#L47
- [x] объекты следует передавать по константной ссылке, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/e3e7619da0c0c49d54e70f258ca530d0c8eba708/lab_01_02_06/01_02_06.cpp#L55-L60

- [x] Почему в выражении участвует firstDigitPosition? Скорее всего, тут ошибка

- [x] wasError следует проверять, если функция его возвращает

- [x] Если исходное число будет равно "-0x80000000" (INT_MIN), то в программе может произойти переполненени

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/e3e7619da0c0c49d54e70f258ca530d0c8eba708/lab_01_02_06/01_02_06.cpp#L47-L53

- [x] out-параметр может оказаться не проинициализированным функцией StringToInt, если ни одна итерация цикла не будет выполнена

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/e3e7619da0c0c49d54e70f258ca530d0c8eba708/lab_01_02_06/01_02_06.cpp#L71-L94

- [x] wasError не используется, хотя будет ошибка, если radix выйдет за допустимые пределы

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/e3e7619da0c0c49d54e70f258ca530d0c8eba708/lab_01_02_06/01_02_06.cpp#L121-L123

- [x] wasError не проверяется между вызовами функции

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/e3e7619da0c0c49d54e70f258ca530d0c8eba708/lab_01_02_06/01_02_06.cpp#L29-L45

- [x] не проверяется выход radix за допустимые пределы

- [x] wasError не инициализируется

- [x] объекты следует передавать по константной ссылке, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению

**Comment by arina-kaa** [comment]
Замечания исправлены.

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/0b2db1ad58b73acc3fabc1c59014881406d50d27/lab_01_02_06/01_02_06.cpp#L79

- [x] Неиспользуемый код

**Comment by alexey-malov** [comment]
https://github.com/arina-kaa/OOP/blob/0b2db1ad58b73acc3fabc1c59014881406d50d27/lab_01_02_06/01_02_06.cpp#L64-L69

- [x] Прежде чем обращаться  к символам строки по индексу, надо проверить ее длину

**Comment by arina-kaa** [comment]
Замечания исправлены.
